src/AppBundle/Entity/Excerpt.php
<?php


namespace AppBundle\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity()
 * @ORM\Table(name="excerpt")
 */
class Excerpt
{
    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    /**
     * @var string
     *
     * @ORM\Column(name="title", type="string", length=255)
     */
    protected $title;

    /**
     * @var string
     *
     * @ORM\Column(name="author", type="string", length=255, nullable=true)
     */
    protected $author;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="date_published", type="datetime", nullable=true)
     */
    protected $datePublished;

    /**
     * @var string
     *
     * @ORM\Column(name="lead_image_url", type="string", nullable=true)
     */
    protected $leadImageUrl;

    /**
     * @var string
     *
     * @ORM\Column(name="excerpt", type="text", nullable=true)
     */
    protected $excerpt;

    /**
     * @var string
     *
     * @ORM\Column(name="url", type="string", unique=true)
     */
    protected $url;

    /**
     * @var string
     *
     * @ORM\Column(name="domain", type="string")
     */
    protected $domain;

    /**
     * @var ArrayCollection
     * @ORM\ManyToMany(targetEntity="AppBundle\Entity\Tag", inversedBy="excerpts")
     * @ORM\JoinTable(name="excerpts_tags",
     *     joinColumns={@ORM\JoinColumn(name="excerpt_id", referencedColumnName="id")},
     *     inverseJoinColumns={@ORM\JoinColumn(name="tag_slug", referencedColumnName="slug")}
     * )
     */
    protected $tags;

    /**
     * @var string
     */
    protected $fullText;

    public function __construct()
    {
        $this->tags = new ArrayCollection();
    }

    /**
     * @return int
     */
    public function getId(): int
    {
        return $this->id;
    }

    /**
     * @param int $id
     */
    public function setId(int $id)
    {
        $this->id = $id;
    }

    /**
     * @return string
     */
    public function getTitle(): string
    {
        return $this->title;
    }

    /**
     * @param string $title
     */
    public function setTitle(string $title)
    {
        $this->title = $title;
    }

    /**
     * @return string|null
     */
    public function getAuthor()
    {
        return $this->author;
    }

    /**
     * @param string|null $author
     */
    public function setAuthor($author)
    {
        $this->author = $author;
    }

    /**
     * @return \DateTime|null
     */
    public function getDatePublished()
    {
        return $this->datePublished;
    }

    /**
     * @param \DateTime $datePublished
     */
    public function setDatePublished(\DateTime $datePublished)
    {
        $this->datePublished = $datePublished;
    }

    /**
     * @return string
     */
    public function getLeadImageUrl()
    {
        return $this->leadImageUrl;
    }

    /**
     * @param string $leadImageUrl
     */
    public function setLeadImageUrl($leadImageUrl)
    {
        $this->leadImageUrl = $leadImageUrl;
    }

    public function getOwnedLeadImageUrl() : string
    {
        $options = ['type' => 'fetch', "width" => 600, "fetch_format"=>"auto"];
        $fetched = cloudinary_url_internal($this->getLeadImageUrl(), $options);
        return $fetched ?: '';
    }
    /**
     * @return string
     */
    public function getExcerpt(): string
    {
        return $this->excerpt;
    }

    /**
     * @param string $excerpt
     */
    public function setExcerpt(string $excerpt)
    {
        $this->excerpt = $excerpt;
    }

    /**
     * @return string
     */
    public function getUrl(): string
    {
        return $this->url;
    }

    /**
     * @param string $url
     */
    public function setUrl(string $url)
    {
        $this->url = $url;
    }

    /**
     * @return string
     */
    public function getDomain(): string
    {
        return $this->domain;
    }

    /**
     * @param string $domain
     */
    public function setDomain(string $domain)
    {
        $this->domain = $domain;
    }

    /**
     * @return Collection
     */
    public function getTags()
    {
        return $this->tags;
    }

    /**
     * @param Collection $tags
     */
    public function setTags($tags)
    {
        $this->tags = $tags;
    }


    public function addTag(Tag $tag) {
        $this->tags->add($tag);
        $tag->addExcerpt($this);
    }

    public function removeTag(Tag $tag) {
        $this->tags->removeElement($tag);
        $tag->removeExcerpt($this);
    }

    /**
     * @return mixed
     */
    public function getFullText()
    {
        return $this->fullText;
    }

    /**
     * @param mixed $fullText
     */
    public function setFullText($fullText)
    {
        $this->fullText = $fullText;
    }
}

src/AppBundle/Controller/ExcerptController.php
<?php

namespace AppBundle\Controller;

use AppBundle\Entity\Excerpt;
use AppBundle\Entity\Tag;
use AppBundle\Form\NewExcerptForm;
use AppBundle\Repository\ExcerptRepository;
use AppBundle\Services\GooseExcerptService;
use Doctrine\DBAL\Exception\UniqueConstraintViolationException;
use Doctrine\ORM\Query\Expr\Join;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Method;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Security;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;

/**
 * @Route("/excerpt")
 */
class ExcerptController extends Controller
{
    /**
     * @Route("/", name="excerpt_index")
     * @Method("GET")
     */
    public function indexAction(Request $request)
    {
        /** @var ExcerptRepository $repo */
        $repo = $this->getDoctrine()->getRepository(Excerpt::class);
        $form = $this->createForm(NewExcerptForm::class,[], [
            'action' => $this->generateUrl('excerpt_convert')
        ]);
        $tag = $request->get('tag', null);

        $limit = $request->get('limit', 25);
        $offset = $request->get('offset', 0);
        $template = $request->get('template', 'index');
        $before = $request->get('before', null);

        $qb = $repo->createQueryBuilder('e')
            ->setMaxResults($limit)
            ->orderBy('e.id', 'DESC');

        if ($tag) {
            $qb->leftJoin('e.tags', 't', Join::LEFT_JOIN)
               ->andWhere('t = :tag')
               ->setParameter('tag', $tag);
        }

        if ($before) {
            $qb->andWhere($qb->expr()->lt('e.id', $before));
        } else {
            $qb->setFirstResult($offset);
        }

        $excerpts = $qb->getQuery()->execute();

        return $this->render("AppBundle:Excerpt:$template.html.twig",[
            'form' => $form->createView(),
            'excerpts' => $excerpts,
            'tag' => $tag
        ]);
    }

    /**
     * @Route("/convert", name="excerpt_convert")
     * @Method("POST")
     * @Security("is_granted('IS_AUTHENTICATED_REMEMBERED')")
     *
     * @return Response
     */
    public function convertAction(Request $request)
    {
        $form = $this->createForm(NewExcerptForm::class,[]);
        $form->handleRequest($request);
        $articleUrl = $form->getData()['url'];

        $excerpt = $this->get(GooseExcerptService::class)->getExcerpt($articleUrl);
        $em = $this->getDoctrine()->getManager();
        $em->persist($excerpt);

        try {
            $em->flush();
        } catch(UniqueConstraintViolationException $ucve) {
            $this->addFlash('info','article already suggested' );
        }

        return $this->redirectToRoute('homepage');
    }

    /**
     * xhr
     *
     * @Route("/{id}/tag/{slug}", name="excerpt_add_tag")
     * @Method({"PUT"})
     * @Security("is_granted('IS_AUTHENTICATED_REMEMBERED')")
     *
     * @return Response
     */
    public function tagExcerptAction($id, $slug = null) {

        $em = $this->getDoctrine()->getManager();

        $excerpt = $em->getRepository(Excerpt::class)->find($id);

        $tag = $em->getRepository(Tag::class)->find($slug);
        if ($tag == null) {
            $tag = new Tag();
            $tag->setSlug($slug);
            $em->persist($tag);
        }
        $excerpt->addTag($tag);

        $em->flush();

        return new JsonResponse([
            'slug' => $tag->getSlug()
        ]);
    }

    /**
     * xhr
     *
     * @Route("/{id}/tag/{slug}", name="excerpt_delete_tag")
     * @Method({"DELETE"})
     * @Security("is_granted('IS_AUTHENTICATED_REMEMBERED')")
     *
     * @return Response
     */
    public function deleteTagExcerptAction($id, $slug = null) {

        $em = $this->getDoctrine()->getManager();

        $excerpt = $em->getRepository(Excerpt::class)->find($id);

        $tag = $em->getRepository(Tag::class)->find($slug);
        if ($tag != null) {
            $excerpt->removeTag($tag);
        }

        $em->flush();

        return new JsonResponse([
            'slug' => $tag->getSlug()
        ]);
    }
}

src/AppBundle/Resources/views/Excerpt/_card.html.twig
<div class="card" data-id="{{ excerpt.id }}">
    <img class="card-img-top img-fluid" src="{{ excerpt.ownedLeadImageUrl }}" alt="{{ excerpt.title }}">
    <div class="card-block">
        <h4 class="card-title">{{ excerpt.title }}</h4>
        <p class="card-text">{{ excerpt.excerpt }}</p>
    </div>
    <div class="card-footer">
        <small class="text-muted">
            <ul class="list-inline">
                <li>{{ excerpt.author }}</li>
                <li><a href="{{ excerpt.url }}">{{ excerpt.url|slice(0, 40) }}</a></li>
                <li>{{ excerpt.datePublished ? excerpt.datePublished|date('d.m.Y H:i') }}</li>
            </ul>
            <div class="tags">
                {% for tag in excerpt.tags %}
                    <span class="badge badge-pill badge-default"><span class="slug">{{ tag.slug }}</span>
                        {% if is_granted('ROLE_ADMIN') %}
                            <i class="fa fa-remove"></i>
                        {% endif %}
                    </span>
                {% endfor %}
            </div>
            {% if is_granted('ROLE_ADMIN') %}
                {% include '@App/components/_add_tag_form.html.twig' with {id : excerpt.id} %}
            {% endif %}
        </small>
    </div>
</div>

src/AppBundle/Resources/views/Excerpt/_cards.html.twig
{% for excerpt in excerpts %}
    {% include 'AppBundle:Excerpt:_card.html.twig' %}
{% endfor %}

src/AppBundle/Resources/views/Excerpt/index.html.twig
<div class="row">
    <div class="col">
        <div class="salvattore-grid" id="excerpt-grid" data-columns data-toggle="infinite-list"
             data-url="{{ path('excerpt_index', {tag: tag|default(null), template: '_cards'}) }}"
             data-last-id="{{ excerpts|last.id }}"
            >
            {% include 'AppBundle:Excerpt:_cards.html.twig' %}
            <a href="#" class="card btn btn-lg btn-black loadmore">More...</a>
        </div>
    </div>
</div>

src/AppBundle/Resources/views/Excerpt/teaser.html.twig
<div id="carouselExampleIndicators" class="carousel slide" data-ride="" >
    <ol class="carousel-indicators">
        {% for excerpt in excerpts %}
            <li data-target="#carouselExampleIndicators" data-slide-to="{{ loop.index }}" class="{{ loop.first ? 'active' }}"></li>
        {% endfor %}
    </ol>
    <div class="carousel-inner" role="listbox">
        {% for excerpt in excerpts %}
        <div class="carousel-item {{ loop.first ? 'active' }}">
            <div class="d-block bz-carousel-image" style="background-image: url('{{ excerpt.ownedLeadImageUrl }}')" alt="{{ excerpt.title }}"></div>
            <div class="carousel-caption d-md-block">
                <h3>{{ excerpt.title }}</h3>
            </div>
        </div>
        {% endfor %}
    </div>
    <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>